### ISSUE TITLE
Server Deployment

### ISSUE THREAD

**Issue by atikrahman-ew** [c19x/C19X-Server#2]
There is no proper guideline for deployment . Kindly share a proper guide to run the project on server as well as gui .

**Comment by c19x** [comment]
Fair point. I shall work on that. Been focused on the app and I wasn't sure if anyone was going to really deploy their own server. Besides, it partly depends on how you would like to deploy it. As a very rough guide to get you started ...

1. Create Ubuntu server / desktop instance
2. Register your own domain (e.g. c19x.org) or use NO-IP to create a fixed domain name as that will be required for HTTPS access
3. Configure server instance and your router for external access, e.g. configure firewalls for HTTP and HTTPS 
4. Install and configure Let's Encrypt CertBot on server instance to enable HTTPS access
5. Look at the scripts in the C19X-Server repo to convert the PEM keys to P12 format
6. Look at C19XHttpsServer.main for server start parameters

If you happen to get all this done successfully, please share your procedure and notes 👍
