### ISSUE TITLE
Help in configuring C19X Server

### ISSUE THREAD

**Issue by BeardyMan37** [c19x/C19X-Server#5]
Hello there. I am using Anydesk to remotely connect to the machine that I'm configuring the server on, and it's already using port 80. So, I'm facing problems. What should I change in order to get the server up and running?

**Comment by c19x** [comment]
Hello! Sorry for the delay in responding. Maybe you can try using SSH to access the remote machine if that is an option. I use SSH to connect to a clean AWS instance and the configuration process was relatively straightforward.
