### ISSUE TITLE
build in Eclipse 

### ISSUE THREAD

**Issue by techy1235** [c19x/C19X-Server#6]
when i run the project after build, I have this problem
Error: Could not find or load main class org.c19x.server.C19XHttpsServer

**Comment by c19x** [comment]
That's weird. This is the command I use to start the server ...

`sudo java -jar release/C19XHttpsServer.jar 443 /opt/c19x/keystore.p12 /opt/c19x/keystore.pw config/parameters.json log/audit.t config/users config/data web web.admin`

You can try running just the basic command and see what happens on your machine ...

`sudo java -jar release/C19XHttpsServer.jar`

It looks like a jar path problem.
